
version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network  
  pgadmin:
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-config/servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network



  backend:
    build:
      context: ./app
      dockerfile: ../Dockerfile.backend
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"   
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=gestor_turnos.settings
    env_file:
      - ./app/.env
    networks:
      - app-network


  frontend:
    build:
      context: ./app/frontend
      dockerfile: ../../Dockerfile.frontend
    volumes:
      - ./app/frontend:/app/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:

  postgres_data:

  pgadmin_data: